language: java

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue

after_success:
  - bash <(curl -s https://codecov.io/bash) -t token

notifications:
  email:
    - pavel_klindziuk@epam.com
    - alena_liamtsava@epam.com
