env:
  global:
  - CODECOV_TOKEN=15648159-3a07-4733-a3ef-72374f94791d
  - secure: DmPlJxNOlXsoAZ55bwyKcP6laM7LiDYwkQF7TupHQYKN8aiT3oIJ1s80HRvwR9yBJbDYMW/Ccf3Fpu15dMsbRODo3d1ev4lwDmrR0agmBM+lxjpcyxqrGaMSNqIs1MXtbdMrAGvwMzNTZrSfECB+HFEqyZlPhfrwZmD6AvAWDSM7YwSd/+n2TwVe7ZaFwrVnphrTweDqxPdqJsnITcAoYfHcflrqlfEaHzf3g0YxMFkyfZzbFuGLyBe36nBhMJUvigC3Y6BcGKbyOehouBaYlIxstT16p6EaOnwFLeIUSkqvI+j8q+GSa3LI3qjbEQVYbGh9OGQBW1CQylF9ALu4v8Luy4VWx8R25P7gV4CJLxhT/R0S4w3xaDjfPuRdDS/ceW+I/IqJLTsTl3Y9vGPC2g6KzlZkXLWXSJSkCUkeBeSAikFb34ODbxeL8MGdLcFzyannGfcFfupKeDIcUHdzVQCDw0pEK69DvqL53nOloUUMCgcUEX8USnkmMMD8ctOdKV6RolgRMRHTdTcO4uVesnsYjUUdV9D1st47+ddiWHk7BVW8+z4NBDMGAtKwZGJA8AQiPqoMNRnsQnvrj2n9T82oiZf3T+Q3E2ddgQkx3pwdrFi+Yz5xNSzWWFc8YiawmMrf4qyKNlSXEO/wP9aoY7+PJsjCMODht+ZglNQEed0=
  - secure: IV3rSZz6J3CH1dJkRxurirO8UIXvFChavoNbLTIWl8Chy8bv2gR5vD5kZo2yoCORMilzOcJuy+WXKZndMJbpGqOa1ngD4wuMWz3fprmisYSdJAfcqXsDQnzgG0mA4FtvrDNF07EVmKc4Y784HWsOj2SGkVS2bQa1nLjAiSAmOwpDYeI3UseKc+XHa0noMmEalRUntd2BP8o1OXdpyaFGf1JeQ8wjcdhKMIByLArijXtbtLBex2F3Kiyb8JCFCJDnDziZ0yiXszVqKfinM98s3l2zZUZxcyLdKSqV2rdvlwIHQt07ZKUUUleUUV7qY3ksJz78VlJWbQMCdK+uA0fyC4pS5CMMyeJizIhPG1ovAJB65U8DE1SeHnhR8fPYEPYVOICOber2/kHvyS9t6EiTindcUCnUfFdlwb5DRtWhb2/ZWurOMyXTXS1ZNThpzBthBhJU2JNPjjyCU2BTjJYbwSFvU1rkJIVoX83thBuIxIhk7Gp6DhJqcZzp+8mnW7fVq41bTK9zDvsJ4UDAumCPRWUxzRqU4yh9He41Nf8kGqW79lOlkH5UjgqzjiEkQc9f13Dq2xpks4vtT1o7OjS27rL/JFVPl5PW4efnZv2iRh2tQkFLOvla3S0sJYRyiByTWzoCQmsBSyvHuMCdkG7LzdDSESG62ngHSn+mS8oXuCg=
language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: $SONAR_TOKEN
services:
- docker
- mysql
before_install:
- chmod +x gradlew
script:
- ./gradlew build -i --continue
- ./gradlew sonarqube
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - pavel_klindziuk@epam.com
  - alena_liamtsava@epam.com
deploy:
  provider: heroku
  api_key:
    secure: S8eRFe9NdCIOauS0Kw8I5/wTBkuyz4M/a4gzROkrYT5IndSSqZw5Cof/K21im4LHnGCQ888BwDFxKdvkdk0KfcGV1I4jIyw2a8Ol3nBMkTe9/AWXkOwMK78Wi8EocBNbPZGDlhjCiQnQ/etes1Mj9/UzrMECd/d8N/jVoRrNbP+ZY4DEAd3dsi/CtX4WggA1hJ9xtQcYQqHnNr9/cNyKpZMNQJm7CnJrUTQtscQO4zPpRMYkT4CdpCuYuiCsv1dHHXxbQ0CbOqjzgaTrnLsl5YAtY3t94LCDjAylQLWUlFXwjvk7wH1ZvVy57NQlksAcabjyh/s7HdGvIq7pWaflgppQ5KPLvZxTaiaX5kr1UEsZ4osqEkVevj0CGP6bDj3RLiulLtJ+sEBCRUXGilJ6zKI3hfRW+9W7A5PFM3MqjDKslsxpFPWr1cOCQymmqi1j9xTeLLOWndup6mVZNQi3M9huDRxH88dqIL0jG0Eo0upuvWX3JjZyfrl5NTckwbjIP3qn4ByHjA1YzXAGgCOKS5zheko8HbllaxJMEM+1sCob/ttmwgiFU9u99MXrsrx+uaSvUKA73n+yqbuwu9CBhphLwxwTWQycrLuif3NzqDMxa5auu1X8zfd+PRWpxXKFmomhDoDMacenVg0/VmXCn8mrL9THIiMR/8zTbPrZ5Yg=
  app: automation-portal
  on:
    repo: klindziukp/automation-portal
