env:
  global:
    - CODECOV_TOKEN=15648159-3a07-4733-a3ef-72374f94791d

language: java

jdk:
  - oraclejdk8

services:
  - mongodb

before_install:
  - chmod +x gradlew

script:
- ./gradlew build -i --continue

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - pavel_klindziuk@epam.com
    - alena_liamtsava@epam.com

deploy:
  provider: heroku
  api_key:
    secure: vbFzWxqKXYtMH+xk+rFv+urqi8c94AHH2LsCdztlaMyEEMVZXCAWp81uQTCHMIm7KJOMA3czejW6I2b9Ud7dtCr+ClDWo0sD685XacsZAdYtocF+nSCktfGNVkWymglGdXWy2hM3Wl9WRIfAoxpSfcplN+uaVKBVWgJu9Oc7zaeivuCce8BgSNxUW2wTGBoQZ3uzzVIDE4LYHdUXyenP+TQ0a8N6xoEXPBw/sWfos/vuGgsnxS9aH5VjMAG2FcYwYH7b6a0F1USjZFcP1bClnrFlXLoQUORfrvjySl+wvrgr4+l34YFEZpWwn9NxHPIzYBkNziLfOVa3CaJLwHvPAUMh24QreZqKdZz5BGe2h4QtbRofqGMMxoamOXJjvp6IbRs4Mel1+7cvaIWggkaJQ0NQH8IxWGFhI00E2z1pfYPnXVY7cdlHwW4k67WgXArq/d8pqIIJJloLcW2Ccp9J+f0IbvXH7cQCJZFPKl2DAyprgXEZSm6jFteyDGIXS9kgw7RfUfwGzsHo0j2OOTtMZ/WpxBiLdrrIilrQDkS7YtBX+3vv4nq09gc6ye6Nf6xJQR8AnTB5aDJuePlAZBOpEvSQ5CEDxZqwM+fw5X3ofOVTtXeMzhSG/9TAGbakW2aVi7bSBywyr5T2gG7+0RjVRIHrdGUxJBpeHhdphM1sl6w=
  app: automation-portal
  on:
    repo: klindziukp/automation-portal