env:
  global:
  - CODECOV_TOKEN=15648159-3a07-4733-a3ef-72374f94791d
  - secure: fZMhxcSaCsUA0Qo96qmEH/x0GwGMwZzVYpDx6kqRorQ/bu5sPfH3xlOvp/v2aluBSO+/+AD8JxxXnqUe2CYPbfaC96cSAyzEKUXMcPXtchLITzppPuFxBvayB1wiHa5tdJtmDisrYZRYNGSE4zqluV9b91tYwvuDepMbqXEmkKxLq/gwnK7xadeUTndUCY3ILgu4lriRxPTGzb/vW7EsnJi7yO+URJtCQgHdeFXR9NQImwns9QJNbomYbx5G59Z/dKc1ztf4f0F+K08CnSmnHoP9a02+ZuZ6PsCM7pOKiGyGgwrHG9ZwFhc8/6V3wUsrxrudWrwx7nDvBnWb8+B59Rvv5XwoDJAedMaTqMvvcNRjW28fQZGD4BMsThFfxIjZw2IziE2INQunqmzqy1eXvSkINV5ORvIQq1UAexWQ/ocFgSXxxdHjzZWdtCdk+5bTny8QLOKjTh3DF6Qhkj6gPrlhhlQDrZif9ZQ4pH3FOfdntBkOLfVpfxcvnnhdNGENBzaBCALRIa8o6GBAOTx6cLAwMLBpiE3FEhNUlVjs5Sh1PPDUI3Yy/Tgq/7HPHpvUSMIjQWXn14/gu3YstwmxiRYV+KJxNnDY5aHRl5MXNeYVJX7Fh4SoauLdPU09n4eJZlbr1sAqNqr/8qPMQ1kADyW4PRBetNqrYaBz/pghI8Q=
  - secure: DRE66z+tpdBZ7RMTw55fMg08h4YWXwD5weABXK12ViIZYL2ObcStauD8tGMZh/92N/3ybNIrP+mIyfZ8UtTVqGW3n7xy8aibpvMzFJsx49w/DIDY70CqjsgurvHjfzH4IU6E/M1MzS8TrIFiCXja3TCu7+7zq1Ik62JSOjm+st8NLtuzO2LxnAQvSemzM3wvDQ3kMfVD8JuOq0BIPT+EIYOyoqVLjrIwiDH3xI1VXy9O3DJGEDwNJT5oTu+FPB//z9EYBGBIj4DJKzNWQxmmANAu8Lu6pDAmNlm2gWmkxSS32V+/FdgHwr3UcrghgXWwgBbCgYwlSFfw/Qbaib3GTHI84gJat+sEO/siA+iNJV6HYDzjgIZ0qvxM9tH2a9k/lRqRS2ehtciFhh5cls2IEHppd1mqVM8nzkKxAusqxZzcXr74fBarhpitrL62j/DIwbp0XJq3rtZ2Ghg6pbAAwzQylh62InmQzz/VrAzaJPlfYLGhj9SYFtYXv5bAr1UL7SBXalhu3+vYGoszGhif8Rlzq+lUcyjd/eUU9p1wNfIvb6LsYuhPmru03nJSBjh5JXzMGsRyyQu7ZsaOpP9uAyPaddZMga/nQ0/dgV+NesGSsDvpRxATKY20ab2HUq8xl3LJ6ElU0SuoYbHrnl6HRza9aY9VfuZDv7237uT2KTM=
language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: $SONAR_TOKEN
services:
- docker
- mysql
before_install:
- chmod +x gradlew
script:
- ./gradlew build -i --continue
- ./gradlew sonarqube
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - pavel_klindziuk@epam.com
  - alena_liamtsava@epam.com
deploy:
  provider: heroku
  api_key:
    secure: S8eRFe9NdCIOauS0Kw8I5/wTBkuyz4M/a4gzROkrYT5IndSSqZw5Cof/K21im4LHnGCQ888BwDFxKdvkdk0KfcGV1I4jIyw2a8Ol3nBMkTe9/AWXkOwMK78Wi8EocBNbPZGDlhjCiQnQ/etes1Mj9/UzrMECd/d8N/jVoRrNbP+ZY4DEAd3dsi/CtX4WggA1hJ9xtQcYQqHnNr9/cNyKpZMNQJm7CnJrUTQtscQO4zPpRMYkT4CdpCuYuiCsv1dHHXxbQ0CbOqjzgaTrnLsl5YAtY3t94LCDjAylQLWUlFXwjvk7wH1ZvVy57NQlksAcabjyh/s7HdGvIq7pWaflgppQ5KPLvZxTaiaX5kr1UEsZ4osqEkVevj0CGP6bDj3RLiulLtJ+sEBCRUXGilJ6zKI3hfRW+9W7A5PFM3MqjDKslsxpFPWr1cOCQymmqi1j9xTeLLOWndup6mVZNQi3M9huDRxH88dqIL0jG0Eo0upuvWX3JjZyfrl5NTckwbjIP3qn4ByHjA1YzXAGgCOKS5zheko8HbllaxJMEM+1sCob/ttmwgiFU9u99MXrsrx+uaSvUKA73n+yqbuwu9CBhphLwxwTWQycrLuif3NzqDMxa5auu1X8zfd+PRWpxXKFmomhDoDMacenVg0/VmXCn8mrL9THIiMR/8zTbPrZ5Yg=
  app: automation-portal
  on:
    repo: klindziukp/automation-portal
