env:
  global:
  - CODECOV_TOKEN=15648159-3a07-4733-a3ef-72374f94791d
  - secure: ds7Bis32jOChS2s6v5SOWb0DNqL/GkZ2pNIiIv2ruN9pB8/e3HQREblsQLhEuNAhxq33q1TudJ//scCkAJjqKqhYG4771u/SOGHXHlcLR9j3lTzqEafhn5aKNie2g4bIWveOOlCT9oeRYhJy0+Timnh6SKLwe3niyKUs20e1nkGCxcp2QBSxVx77bKm/wM6SA3cFxPmzNLuNEFEkIPRx3dRI1VoQXr1Dna+M0v3ye60omiIwjn9wErW3EN6HyGjzJBAReZmqn2v2YMBAeolArG8+jQnT768a30vQ/LQHSOLOw3xsBQMq2+fjeCOiAg5vhs6JYLXLuPrrmE7wXgN1basJIh4FmSu/n8zPR7oxerLa07xZXcd8xB4Z5iX/HTtVJOayUAHvhWVewc3lwJM9tE1E8TF0Ipm5CIx0w8YnIWwgr4fsLsOoYw4mObP3aq25kU5yjb3gPr2eR16/NX7AI9mbml5XOE2eJRV9mVwb4eHdPtdwXaD+P+g3VXEWzPCRS8OwtZV/oLeLZ7OUFARicM2Q0MOxq4izLuTHVh1Y0A6YijXT91gL5MGX4uHrytkHGApUOdWxrIMcWLnn9EFX/dMlms2Ubn/oHxv/y8BhIvph0u9TlE8TSxtel5D0m0XWk9LrMaKUFdjoEJoMxYisAJj+vuN5AATzgKJx82S0Fcc=
  - secure: oiKiT6P1zyVRH0Xb6pb8gMp12P+9LhOtqF/5m0Zl7BEoOda+GXPfq4eOxgz9zGiBcbjzzbjcrmJl5ZdsICcyQAK1fb0r04Jtw14tEUgei5EH2EaP7QpSOel5X+TUSlWqlgbh8Gkj9lnrBd4qaYI4MO1hz/Fvc61on10LDBfgfmR8PQ1zkGl2DTJwZkrylD56A5MbDmW9/do/DwRDRLGwvM8J8RvygZ2z646cjZs06ipAR/WCdbPfuiBqMCIyoO/Q+i4Dy9D0RdDGndJgdlj9ttiQoXpbFHwXsvBEFGIR+b6CmyIFperCOqgVK+OVM9QJWcNTNCTP8vTYZcsLvPPFwuxqC4g3Bi1TA2dTmKfmbKwGPQ9QH3Aw5/HhwSVoU5ggkvqyx1Bvt/XeYIi3cefDCyJu62GisTiD7KePASs/zjm4wxsyivOJbxWlwsQnCE6fLrtlQQLRiloleHuZXmE23DowKElrejVSe/c3zvGEo5Y3y4KhzuR5r2m4XVzZVk8vq+vLF+cTjCACqOm0XceUQtvxnimMaNSFMwMaMBPTNnt5UhU3Na3uCforFTa+/d2urs7tMtSHB+VHG6ZIUiGsE9gU7ZulCx3WrhGvRgpNGX4W2o5dAup/hoQqDfoMNREBGGpQqlawXhLQbV4EhcLx9bjWGqtreKI6fduTYnH8Wz0=
  - secure: kM/YIU3Bkkdidr9ptd+8u2jdOXJn4QNqh204vLbmU0/PiQu85yGu9+nkn96/fvpqAN/f1PnpaZJQQ9ckizJKRJFRv/iS3R0DMPua/DRM2QqbKTV/mo6+mGLxWmQTAn5M3qhJrNwqDktTiHdNJu0oWMF5anpeiWs4fEnoCzeRCQXVvFTIqdEztEr9nsNGlqlcIKfVJcGHNKvLwBAilI33IyX2HgXFi79OwQCxZx6cabSKgiEizRyK+jkwFwgXcDxQV0sLsLEsKVVa6oopcsqpuABM0dkk/crQFJx73sqVzcMj5B1df8qnUly2HI2VlKP/JBrNZZruaQuQ87akq0isqtqIn0iGbqr5MqQW9zVFh/K/hzn+S1xfZtay6Tp4nGv3b22b4dgKdsZ98Edj+VRdAr8FZ28bw3y1JTNSU/2H2mjIA69KlRmET76DRsSIrCb/CCEL5/NNEeQpEyM8QFvhP2X+zLueivK88J0fZuUTvnmeEia3zO595gRCp3R3A0E48Aps+h8NIZw3w4rR08Dqy3wv3I7BJlVPl/J+Hy88gCcmgaez9KSUKH38IAdyTJ1QrjAktEA10zBHX9ecLpkury1fuZODyajH7zv0aiS9WmOvM4EJKMecJy4y06O+WS6bnYPaIkGfDpB30kQu2RMQA0LTLo2tDfQF338mrcEUaaw=
language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: "$SONAR_TOKEN"
services:
- docker
- mysql
before_install:
- chmod +x gradlew
script:
- "./gradlew build -i --continue"
- "./gradlew sonarqube"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - pavel_klindziuk@epam.com
  - alena_liamtsava@epam.com
deploy:
  provider: heroku
  api_key:
    secure: S8eRFe9NdCIOauS0Kw8I5/wTBkuyz4M/a4gzROkrYT5IndSSqZw5Cof/K21im4LHnGCQ888BwDFxKdvkdk0KfcGV1I4jIyw2a8Ol3nBMkTe9/AWXkOwMK78Wi8EocBNbPZGDlhjCiQnQ/etes1Mj9/UzrMECd/d8N/jVoRrNbP+ZY4DEAd3dsi/CtX4WggA1hJ9xtQcYQqHnNr9/cNyKpZMNQJm7CnJrUTQtscQO4zPpRMYkT4CdpCuYuiCsv1dHHXxbQ0CbOqjzgaTrnLsl5YAtY3t94LCDjAylQLWUlFXwjvk7wH1ZvVy57NQlksAcabjyh/s7HdGvIq7pWaflgppQ5KPLvZxTaiaX5kr1UEsZ4osqEkVevj0CGP6bDj3RLiulLtJ+sEBCRUXGilJ6zKI3hfRW+9W7A5PFM3MqjDKslsxpFPWr1cOCQymmqi1j9xTeLLOWndup6mVZNQi3M9huDRxH88dqIL0jG0Eo0upuvWX3JjZyfrl5NTckwbjIP3qn4ByHjA1YzXAGgCOKS5zheko8HbllaxJMEM+1sCob/ttmwgiFU9u99MXrsrx+uaSvUKA73n+yqbuwu9CBhphLwxwTWQycrLuif3NzqDMxa5auu1X8zfd+PRWpxXKFmomhDoDMacenVg0/VmXCn8mrL9THIiMR/8zTbPrZ5Yg=
  app: automation-portal
  on:
    repo: klindziukp/automation-portal
