env:
  global:
  - CODECOV_TOKEN=15648159-3a07-4733-a3ef-72374f94791d
  - secure: qhJfX+Fju2uYnigoaC30dOQRimpX0AoM7r8auzhLlgRF39Cw4oaw7kUYlcKksO4d2g5J0zf9rgunvMSBdtsOSavYt802/wpBotlu1aG5UOVbGan3/QxdvylBpN86lAH5pUpTemBEIPoilsEuK0AhhmCRuswSdmQJytgGHEBjf/70zU4IYmWS9Pt21yMvNl7zpku2S0sX3eBAWIIE9gyXM5H/k07K5igrSvC5CatOf5alC9500VKlL2D/r/LgLVUcEaIp1+GcYMPfA9Ne9x3AaPetrIZgVZaOmuM/tfLwYgDi7I/lHIPfpycSiooLLKbVQx/ZtrEsyeTJyTsffo71GZkiuDHyOO4CHFzdlS9JaBToNQ7ttyDug6a6htTrvY4ISvcNbtmwwY4zlpvwJMIpDn8AQSGjreQ7qZbZotBKnCG49Hj9v3xsa7CqC6FMNCd2G6du7Xdi3I4RRXYu0WW2OWvabJ08dUGk2IKH8llzfCb4WIZcu/LJ+dwEcjSE8M42xv8Y61TDbJPalhsYHNpOlpf433GHqxsewNUxIU9B07Mko1u6M1nUosHq4OOalvu7Hq5erafpCTKGMEJsAFeficoKg7XXfX0TMdRa7FpTrLg693oJwiWZAWD1s2+b9oM6vtntF2hsnR6EiAxslwi1OybtNVoL4hgEB0shsBAYS3s=
  - secure: QGFQO5xLIJp5FIIaArdBjfjbJiPRxtx2Ue1KxidjSK2CryEklkan5yP3AiA2dcGEJIcq5C2l2LSpvbmC/3tsOQyzov3yOsCSToOKO6f+aN1HlAmxVjURBGCjaqCG85L35MEsTcyR9YklV6ymprnmXHjEREjAnzzp9wsqOZgkQRjYY2MQhYblT0hfRngQz78nVqYgdNB461MSantwYMQKJERl93nxojL0yu2R9KdtV7xrVkBpuTSKXxqm8xyo1JX5H3aP8OU5+ea+IooVXP4iNqTVUrahT0vU1OWqIXdvQTJR9YHPfnf6Uv/4XFmASM5gCsapSMuttrma7Z2RtmQ2qkCYVx7Uwhb2Zn75zc1wHw5+jSL9u2DYaSWYV/wspSi2OBmYeMSN477+3P9vcxE83N7L3rPnkve2+8VTICH1SPHUOBwO6VLHPV5eSv7lL3c7s7QDAmgVaRGsrbh2CXC44uVELUSPG/nDBpmWf5jVUbDUBd2LskhLHyyZVjcFpOusS867H9GjzQEN0nU5A54DibDqD/YInS8rfZDm/ERpTP64FTa0m3joEv0zls7wFfolPG1SrlsHYJNjmh96Af7xQXanaDbfMEpIxDp/tqkqNXEOisRwkLAt4yS4MrmR+KdMQa1kpg7VF6Lxo1F29qw2hhfpdO59iN6bliyuzQiuyKw=
  - secure: d89fFh/HuV4+xHa4eCRkfwe1PUdW677pAnFk9wWeCfH1Qj8qEWUQCSicZ+d4NKXKuIOny4kpv+7cNZRQN1sGC/+vrZ2xuR/Ft6B/TMZLIEzRziDpHoVi8citVhcIdYsrr1HeIEzQZCFRODytCaBj0iH36taaytLnT6PhbszO2dzSGT8Govp+aHRIOxMXWRNeTfcaltI0TxN44dUoWDJdJVxVzmpC4BvPWUwu0frHBYh6XbYAF3r18Kd35BuwxDWcSzYXwRrNdabzQqCqmJCT4N1vchGOyjewp9NgKey2/4NF2xf3pH+c4UMBIuAZG+Z+xs3gUZZ41YFL24rleQf6/KWkTeTS7uo/kGKEKk0eBRx1jwNCg+AdOIE1r7S542m8adf7D/aNVMW6LA4tM105ifv6UoSkHtuTSiIDpIFwFmEaDTepmPf5zHrdhQxC7oMEYHsjZn2eaAecMvkJ1MtiUypbCurIEoEtp+bmt+7UKR402031Kvuu7tq6RwJeuXhY4JuQjUmOy7k5f/+JgtoqXUeiUYfk+ICIks6BIjz96zba57vi124/Vau+yvQtby78RaxdJg464qgiu9pSqJKjB58l/J+q3loHQSnG2uwYhZkCuJttniFuv15hcALSv/I9xQZC47PR1OXV703EbDKMoDP82k9qEl54imLxTu2Wcn8=
language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: d89fFh/HuV4+xHa4eCRkfwe1PUdW677pAnFk9wWeCfH1Qj8qEWUQCSicZ+d4NKXKuIOny4kpv+7cNZRQN1sGC/+vrZ2xuR/Ft6B/TMZLIEzRziDpHoVi8citVhcIdYsrr1HeIEzQZCFRODytCaBj0iH36taaytLnT6PhbszO2dzSGT8Govp+aHRIOxMXWRNeTfcaltI0TxN44dUoWDJdJVxVzmpC4BvPWUwu0frHBYh6XbYAF3r18Kd35BuwxDWcSzYXwRrNdabzQqCqmJCT4N1vchGOyjewp9NgKey2/4NF2xf3pH+c4UMBIuAZG+Z+xs3gUZZ41YFL24rleQf6/KWkTeTS7uo/kGKEKk0eBRx1jwNCg+AdOIE1r7S542m8adf7D/aNVMW6LA4tM105ifv6UoSkHtuTSiIDpIFwFmEaDTepmPf5zHrdhQxC7oMEYHsjZn2eaAecMvkJ1MtiUypbCurIEoEtp+bmt+7UKR402031Kvuu7tq6RwJeuXhY4JuQjUmOy7k5f/+JgtoqXUeiUYfk+ICIks6BIjz96zba57vi124/Vau+yvQtby78RaxdJg464qgiu9pSqJKjB58l/J+q3loHQSnG2uwYhZkCuJttniFuv15hcALSv/I9xQZC47PR1OXV703EbDKMoDP82k9qEl54imLxTu2Wcn8=
services:
- docker
- mongodb
before_install:
- chmod +x gradlew
script:
- ./gradlew build -i --continue
- ./gradlew sonarqube
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - pavel_klindziuk@epam.com
  - alena_liamtsava@epam.com
deploy:
  provider: heroku
  api_key:
    secure: S8eRFe9NdCIOauS0Kw8I5/wTBkuyz4M/a4gzROkrYT5IndSSqZw5Cof/K21im4LHnGCQ888BwDFxKdvkdk0KfcGV1I4jIyw2a8Ol3nBMkTe9/AWXkOwMK78Wi8EocBNbPZGDlhjCiQnQ/etes1Mj9/UzrMECd/d8N/jVoRrNbP+ZY4DEAd3dsi/CtX4WggA1hJ9xtQcYQqHnNr9/cNyKpZMNQJm7CnJrUTQtscQO4zPpRMYkT4CdpCuYuiCsv1dHHXxbQ0CbOqjzgaTrnLsl5YAtY3t94LCDjAylQLWUlFXwjvk7wH1ZvVy57NQlksAcabjyh/s7HdGvIq7pWaflgppQ5KPLvZxTaiaX5kr1UEsZ4osqEkVevj0CGP6bDj3RLiulLtJ+sEBCRUXGilJ6zKI3hfRW+9W7A5PFM3MqjDKslsxpFPWr1cOCQymmqi1j9xTeLLOWndup6mVZNQi3M9huDRxH88dqIL0jG0Eo0upuvWX3JjZyfrl5NTckwbjIP3qn4ByHjA1YzXAGgCOKS5zheko8HbllaxJMEM+1sCob/ttmwgiFU9u99MXrsrx+uaSvUKA73n+yqbuwu9CBhphLwxwTWQycrLuif3NzqDMxa5auu1X8zfd+PRWpxXKFmomhDoDMacenVg0/VmXCn8mrL9THIiMR/8zTbPrZ5Yg=
  app: automation-portal
  on:
    repo: klindziukp/automation-portal
