kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume
  namespace: ap-dev
  labels:
    type: development
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: ap-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  selector:
    matchLabels:
      type: development
